import { useRef, useState, useEffect } from 'react'
import { createPortal } from 'react-dom'
import { Modal } from 'react-bootstrap'
import { EmpresaDataForm, defaultDataEmpresa } from '../../../interfaces/Configuracion/EmpresaDataForm';
import { StepperComponent } from '../../../_metronic/assets/ts/components'
import { KTIcon } from '../../../_metronic/helpers'
import { Step1 } from './Stepper-Empresa/Step1'
import { Step2 } from './Stepper-Empresa/Step2'
import { Step3 } from './Stepper-Empresa/Step3'
import { Step4 } from './ods-stepper/Step4'
import { Step5 } from './ods-stepper/Step5'